language: node_js
node_js:
  - 6
  - node
before_install:
  - npm install -g npm@2.14
notifications:
  slack:
    secure: nZuo5NTQAQXjg/D1Mz0yLDph9OQNFBRIDwTXWPsEHMCjWuCIxGby85O55ufwCLF+fY2NVKPYEJQG8Cph3fjZezTK7OBys+I51Zf8rluaRlkQP6WRKTx/qI/5aohnAZn/mPnF08NNuT1DIPs316m34KlsgR/JPrbyKHeJL6adOR8=
sudo: false
env:
  secure: "NTJCI1UgSy3mui1N7iN7krcFtzXfnwnROoQPsfcg5E/cNi0lDysobjzQAa2YUKnWMv2IO9aYw7jkkF9h3xKMT/jvSCCInwp5q9zjWNM6etkpEf2nUVjsFhQHSdRiB0QIQSvaACF08ZNOlLJacIK/T+CpmaUcETggQnIHk6cXF24="
